### ISSUE TITLE
Cannot Build from Source

### ISSUE THREAD

**Issue by Kleptine** [eliemichel/OpenMfxForBlender#31]
The instructions mention to follow the same standard Blender build instructions, but after:
 `make.bat update`
and
 `make.bat`

I get compilation errors in the USD code:
```
Error C2039 'Bind': is not a member of 'usdBlender__pxrReserved__::UsdShadeMaterial' bf_usd C:\Users\klept\Documents\OpenMeshEffectsBlender\OpenMeshEffectForBlender\source\blender\io\usd\intern\usd_writer_mesh.cc 347
Error C2039 'Bind': is not a member of 'usdBlender__pxrReserved__::UsdShadeMaterial' bf_usd C:\Users\klept\Documents\OpenMeshEffectsBlender\OpenMeshEffectForBlender\source\blender\io\usd\intern\usd_writer_mesh.cc 347
```

![devenv_LSCqB6gnYI](https://user-images.githubusercontent.com/1078792/87172933-dfd7ee80-c289-11ea-8ac7-f680bd855d76.png)

**Comment by Kleptine** [comment]
FYI, the latest version of `lib/` is 2.90, so pulling this repo and running `make update` actually pulls 2.90, instead of 2.83.1. 

To fix, delete your `lib/win64_vc15` folder and run the command:
```svn co https://svn.blender.org/svnroot/bf-blender/tags/blender-2.83.1-release/lib/win64_vc15/```

This pulls the correct version of the dependencies.

See further discussion here: 
https://blender.chat/channel/blender-builds?msg=tSNWmyCaeWN3c7RB7

**Comment by Kleptine** [comment]
Copy-pasting, to avoid link rot: 
![image](https://user-images.githubusercontent.com/1078792/87175799-05ff8d80-c28e-11ea-894f-a09e37b3e7eb.png)

**Comment by eliemichel** [comment]
Hi @Kleptine thanks a lo for this feedback! This is an issue I am likely to run it myself eventually and that I wasn't aware of, good to know.
So I assume that once the correct lib/ is used it works ok, right?

PS: I always fork from tagged releases, updating from time to time to the latest release.

**Comment by Kleptine** [comment]
Yeah, this builds fine after following the steps from the discussion.

**Comment by Kleptine** [comment]
Also, FYI, I didn't even realize there were binaries! After all of this I realized I could have just downloaded it. T.T

**Comment by eliemichel** [comment]
Well it's not lost work, it actually helps me to have people try and build it to be sure I did thinks properly. :)
