### ISSUE TITLE
Reload effect while holding values

### ISSUE THREAD

**Issue by Yamjin** [eliemichel/OpenMfxForBlender#33]
Hi! I'm using this excellent modifier!

Is it possible to reload effect while holding values?
I change effect frequently when making models. When effect is changed, OpenMeshEffect modifier does not reflect this change. For that, I change effect to "no effect" and reset the effect. But, By doing this, values of parameters are intialized and needed to reset these values: It takes time to do this.
It is very helpful to enable to reload effect while holding values of parameters.

thanks!

**Comment by eliemichel** [comment]
Hi @Yamjin nice suggestion!
Out of curiosity, with which OpenMeshEffect plugin do you use this?

**Comment by Yamjin** [comment]
Thank you for your reply!

I use this with MfxHoudini. I update effect as follows  while running Blender and Houdini at the same time.
In Houdini, open .hda file, edit parameters and nodes, and save .hda file.
Next, in blender, set "no effect" and reset to reload effect, and reset values of parameters manually.
(Sometimes, Blender crashes when values are edited after resetting the effect. )
If the work of Blender is done done by one-click, it's very helpful.

**Comment by eliemichel** [comment]
Should be good with this new release: https://github.com/eliemichel/OpenMeshEffectForBlender/releases/tag/mfx-v0.10.0

**Comment by Yamjin** [comment]
EXCELLENT!! This is which I wished for.
Thanks!
