### ISSUE TITLE
Linux build

### ISSUE THREAD

**Issue by tkarabela** [eliemichel/OpenMfxForBlender#52]
Hi @eliemichel, I made a Linux release build (x86_64, Ubuntu 20.04) for the latest version 0.12 of OpenMeshEffect Blender (5b8b30af). GitHub won't let me attach it to the ticket due to filesize, so I put it up here: https://drive.google.com/file/d/1bfnS_I_71Fv1Tl8_8WSn8D0YdIRglNXs/view?usp=sharing

A new MfxVTK release is coming as well, once I'm done with refactoring to support transforms/extra inputs/attribute requests :)

**Comment by eliemichel** [comment]
Thanks a lot! :) I've updated the release.
