### ISSUE TITLE
[Request] Could we get to see binaries for this project?

### ISSUE THREAD

**Issue by ItsCubeTime** [eliemichel/OpenMfxForBlender#55]
[Request] Could we get to see binaries for this project?

Also curious if it would be possible to build it for the latest release, 2.92? <3

**Comment by eliemichel** [comment]
Hello @ItsCubeTime ,

Binaries are available in the Release section: https://github.com/eliemichel/OpenMeshEffectForBlender/releases/tag/mfx-v0.12.0

They are based on an early version of 2.92, next rebase is going to be on 2.93 alpha!

**Comment by ItsCubeTime** [comment]
> Hello @ItsCubeTime ,
> 
> Binaries are available in the Release section: https://github.com/eliemichel/OpenMeshEffectForBlender/releases/tag/mfx-v0.12.0
> 
> They are based on an early version of 2.92, next rebase is going to be on 2.93 alpha!

Thats awesome, will def. be trying this out. 

I saw your thread on https://devtalk.blender.org/t/open-mesh-effect-branch-prev-houdini-engine-modifier-for-blender/8218/95

Personally I would love to see this get adopted and included in official Blender versions, I think the concept of a universal modifier langauge/format is fantastic as the industry is kind of lacking when it comes to standardization currently.

Who knows, if Blender adopts it maybe other softwares will start adding support for it as well.

And when it comes to GPL, one could argue OpenMeshEffects to just be a fancy exporter/importer tool (really thats what it is). So the people over in that thread exaggerated the whole licensing situation quite a lot tbh.

I would try get in touch with Ton Rosendahl and see what he thinks about it, maybe he has a different point of view than the developers who responded on your thread (I happen to know his email is ton@blender.org, tho Im not sure he actually wants to be contacted by this adress). 

Really this is something that can improve the workflow of every 3D artist who does procedural modeling and I highly doubt Blender's geometry nodes project will ever get on pair with what a software like Houdini FX can do (tho I certainly hope it will).
