### ISSUE TITLE
macOS build of v0.14.0

### ISSUE THREAD

**Issue by JohJakob** [eliemichel/OpenMfxForBlender#57]
I’ve compiled v0.14.0 for macOS (requires macOS 10.13 High Sierra or later). The modifier is there, but I didn’t test it with an effect.

*Note: This build is not signed. To open it, control + click on the app and control + click on “Open”. Click “Open” in the dialogue that appears.*

[Download via WeTransfer](https://we.tl/t-wGMYpJDQql)

**Comment by eliemichel** [comment]
Thanks a lot! I've added it to the release :)
