### ISSUE TITLE
I can't compile it.

### ISSUE THREAD

**Issue by SetoKaiba** [eliemichel/OpenMfxForBlender#58]
I got this error when I try to compile.
fatal error C1083: Cannot open include file: “mfx
Host.h”: No such file or directory [G:\Seto\GitHub\SetoKaiba\build\intern\openmfx\test\openmesheffect_plugin_load_test.
vcxproj]

I change the foldername to blender.git and compile it by the commands below.
python build_files\buildbot\worker_update.py windows_openmfx openmfx
python build_files\buildbot\worker_compile.py windows_openmfx openmfx

I check the intern\openmfx\test\CMakeLists.txt
It seems that the include folder is set to be ".".
mfxHost.h is in "..\host".

**Comment by eliemichel** [comment]
Thanks for the feedback! The unit test file was slightly outdated, should be fixed by 704c4ed.
