### ISSUE TITLE
Update to the latest blender 3.6 LTS

### ISSUE THREAD

**Issue by fire** [eliemichel/OpenMfxForBlender#85]
https://www.blender.org/ 3.6 LTS

![image](https://github.com/eliemichel/OpenMfxForBlender/assets/32321/e4a564c2-412d-4b40-be5b-1a06ebfb9286)

**Comment by eliemichel** [comment]
Yep I'll do this eventually!

**Comment by fire** [comment]
Closing because Blender 4.0 is out https://www.blender.org/download/releases/4-0/. Make a new issue to tracker Blender 4.0.
